version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
  chatapp:
    image: usha5000/chatapp
    restart: always
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis